#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."
if [[ $# -lt 2 ]]; then
    echo 'Usage: scripts/build SOURCE.mojo OUTPUT [COMPILER_FLAGS...]' >&2
    exit 2
fi
source ./scripts/native-libraries
mojo_s3_source="$1"
mojo_s3_output="$2"
shift 2
mkdir -p "$(dirname "$mojo_s3_output")"
./scripts/mojo build -I src -I tests -Xlinker "$mojo_s3_crypto" -Xlinker "$mojo_s3_curl" -Xlinker "$mojo_s3_xml" "$@" "$mojo_s3_source" -o "$mojo_s3_output"
