"""Offline fixture generator ONLY; botocore is never an SDK runtime dependency."""
import json
import random
from pathlib import Path
from urllib.parse import quote
import botocore
from botocore.auth import S3SigV4Auth
from botocore.awsrequest import AWSRequest
from botocore.credentials import Credentials

rng = random.Random(74391)
rows = []
for index in range(64):
    key = "".join(rng.choice("azAZ09 /%+?&#=é雪._-") for _ in range(24))
    path = "/bucket/" + quote(key, safe="/~")
    query = [
        ("prefix", "".join(rng.choice("a %+=é") for _ in range(6))),
        ("duplicate", "z"),
        ("duplicate", " a"),
        ("empty", ""),
    ]
    payload = ("payload-é-" + str(index)) if index % 2 else ""
    method = ["GET", "PUT", "HEAD", "DELETE"][index % 4]
    creds = Credentials(
        "TESTACCESS",
        "test-secret-fixture",
        "test-session-token" if index % 3 == 0 else None,
    )
    req = AWSRequest(
        method=method,
        url="https://example.test:9443" + path,
        data=payload.encode(),
        params=query,
    )
    req.headers["Host"] = "example.test:9443"
    req.headers["X-Amz-Meta-Note"] = "  a  b\t c  "
    req.headers["X-Amz-Meta-Duplicate"] = "first"
    req.headers["X-Amz-Meta-Duplicate"] = " second  value "
    req.context["timestamp"] = "20261004T120000Z"
    signer = S3SigV4Auth(creds, "s3", "us-east-1")
    signer._modify_request_before_signing(req)
    canonical = signer.canonical_request(req)
    string_to_sign = signer.string_to_sign(req, canonical)
    signature = signer.signature(string_to_sign, req)
    rows.append(
        dict(
            method=method,
            path=path,
            query=query,
            headers=list(req.headers.items()),
            payload=payload,
            token=creds.token or "",
            canonical=canonical,
            signature=signature,
        )
    )
root = Path(__file__).resolve().parents[1]
(root / "tests/fixtures/signing.json").write_text(
    json.dumps(
        {
            "generator": "botocore " + botocore.__version__,
            "seed": 74391,
            "cases": rows,
        },
        ensure_ascii=False,
        indent=2,
    )
    + "\n"
)
q = lambda s: json.dumps(s, ensure_ascii=False)
lines = [
    "# Generated by scripts/generate_signing_fixtures.py; synthetic credentials only.",
    "from std.collections import List",
    "from std.testing import assert_equal",
    "from mojo_s3.protocol import Field",
    "from mojo_s3.signing import Credentials, sign",
    "from mojo_s3.crypto import hash_text",
    "",
]
for case_index, row in enumerate(rows):
    lines += ["def case_" + str(case_index) + "() raises:"]
    fields = (
        lambda values: "["
        + ", ".join("Field(" + q(k) + ", " + q(v) + ")" for k, v in values)
        + "]"
    )
    lines += [
        "    var query: List[Field] = " + fields(row["query"]),
        "    var headers: List[Field] = " + fields(row["headers"]),
        '    var result = sign(Credentials("TESTACCESS", "test-secret-fixture", '
        + q(row["token"])
        + '), "us-east-1", "s3", '
        + q(row["method"])
        + ", "
        + q(row["path"])
        + ", query, headers, hash_text("
        + q(row["payload"])
        + '), "20261004T120000Z")',
        "    assert_equal(result.canonical_request, "
        + q(row["canonical"])
        + ")",
        "    assert_equal(result.signature, " + q(row["signature"]) + ")",
    ]
    lines += [""]
lines += (
    ["def main() raises:"]
    + ["    case_" + str(i) + "()" for i in range(len(rows))]
    + [
        '    print("64 deterministic botocore differential signing fixtures passed")'
    ]
)
(root / "tests/test_signing_differential.mojo").write_text(
    "\n".join(lines) + "\n"
)
print("Generated 64 reference fixtures using botocore", botocore.__version__)
